### ISSUE TITLE
pub/sub publish to specific topic

### ISSUE THREAD

**Issue by piresbruno** [autozimu/Nanomsg.swift#1]
Hi, i've been playing around with Nanomsg, and wanted to ask how can i publish to a specific topic?

I've used subscriber.sub_subscribe = "" (found it on the examples),  tested and noticed it seems to filter by topic, but i don't find a place to define the publisher message topic.

Can you please give me some hint?

**Comment by autozimu** [comment]
As far as I understand, you cannot publish to specific topic. Every message published will go into the stream. It is the subscriber's responsibility to define filters/topics to pickup only messages it is interested in.

**Comment by piresbruno** [comment]
Thanks for the clarification!
